name: Maven Build & Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Get Commit Info
        id: commit
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          COMMIT_MSG_URL_ENCODED=$(git log -1 --pretty=%B | jq -sRr @uri)
          echo "commit_message=${COMMIT_MSG_URL_ENCODED}" >> $GITHUB_OUTPUT

      - name: Build with Maven
        id: build
        run: |
          VERSION="build-${{ github.run_number }}-${{ steps.commit.outputs.sha_short }}"
          mvn -B package --file pom.xml -DskipTests -Drevision=${VERSION}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Deploy to Update Server
        run: |
          JAR_FILE=$(find target -name "CoreProtectTNT-*.jar")
          
          curl -X POST \
               -H "X-API-KEY: ${{ secrets.UPDATE_SERVER_API_KEY }}" \
               -H "Content-Type: application/octet-stream" \
               --data-binary "@${JAR_FILE}" \
               "${{ secrets.UPDATE_SERVER_URL }}?version=${{ steps.build.outputs.version }}&changelog=${{ steps.commit.outputs.commit_message }}"