name: Maven Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Get Commit Info
        id: commit
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Deploy to Update Server
        run: |
          VERSION="build-${{ github.run_number }}-${{ steps.commit.outputs.sha_short }}"
          JAR_FILE=$(find target -name "CoreProtectTNT-*.jar")
          
          curl -X POST \
               -H "X-API-KEY: ${{ secrets.UPDATE_SERVER_API_KEY }}" \
               -F "file=@${JAR_FILE}" \
               -F "version=${VERSION}" \
               -F "changelog=${{ steps.commit.outputs.commit_message }}" \
               "${{ secrets.UPDATE_SERVER_URL }}"