name: Maven Build & Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Get Commit Info
        id: commit
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          COMMIT_MSG_B64=$(git log -1 --pretty=%B | base64 -w 0)
          echo "commit_message_b64=${COMMIT_MSG_B64}" >> $GITHUB_OUTPUT

      - name: Build with Maven
        id: build
        run: |
          VERSION="build-${{ github.run_number }}-${{ steps.commit.outputs.sha_short }}"
          mvn -B package --file pom.xml -DskipTests -Drevision=${VERSION}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoreProtectTNT-JAR
          path: target/CoreProtectTNT-*.jar
          retention-days: 7

      - name: Notify
        run: |
          ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
          JSON_PAYLOAD=$(printf '{"version": "%s", "changelog_b64": "%s", "artifact_url": "%s", "github_token": "%s"}' \
            "${{ steps.build.outputs.version }}" \
            "${{ steps.commit.outputs.commit_message_b64 }}" \
            "${ARTIFACT_URL}" \
            "${{ secrets.GITHUB_TOKEN }}")
          
          curl -X POST \
               -H "X-API-KEY: ${{ secrets.UPDATE_SERVER_API_KEY }}" \
               -H "Content-Type: application/json" \
               -d "${JSON_PAYLOAD}" \
               "${{ secrets.UPDATE_SERVER_URL }}"